# SPDX-FileCopyrightText: Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Integration test

on:
  pull_request:
  push:
    branches:
      - main
      - stable*

env:
  APP_NAME: text2image_stablediffusion2

concurrency:
  group: integration-test-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  transcription:
    runs-on: ubuntu-22.04

    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        php-versions: [ '8.1' ]
        databases: [ 'sqlite' ]
        server-versions: [ 'master' ]

    name: Integration test on ☁️${{ matrix.server-versions }} 🐘${{ matrix.php-versions }}

    env:
      MYSQL_PORT: 4444
      PGSQL_PORT: 4445

      PYTHONUNBUFFERED: 1
      APP_HOST: 0.0.0.0
      APP_ID: text2image_stablediffusion2
      APP_PORT: 9080
      APP_SECRET: 12345
      COMPUTE_DEVICE: CPU
      NEXTCLOUD_URL: http://localhost:8080

    services:
      mysql:
        image: mariadb:10.5
        ports:
          - 4444:3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        options: --health-cmd="mysqladmin ping" --health-interval 5s --health-timeout 2s --health-retries 5
      postgres:
        image: postgres
        ports:
          - 4445:5432/tcp
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: rootpassword
          POSTGRES_DB: nextcloud
        options: --health-cmd pg_isready --health-interval 5s --health-timeout 2s --health-retries 5

    steps:
      - name: Checkout server
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}

      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_mysql, pdo_sqlite, pgsql, pdo_pgsql, gd, zip

      - name: Checkout app
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          path: ${{ env.APP_NAME }}

      - name: Get app version
        id: appinfo
        uses: skjnldsv/xpath-action@7e6a7c379d0e9abc8acaef43df403ab4fc4f770c # master
        with:
          filename: ${{ env.APP_NAME }}/appinfo/info.xml
          expression: "/info/version/text()"

      - name: Set up Nextcloud
        if: ${{ matrix.databases != 'pgsql'}}
        run: |
          sleep 25
          mkdir data
          ./occ maintenance:install --verbose --database=${{ matrix.databases }} --database-name=nextcloud --database-host=127.0.0.1 --database-port=$MYSQL_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass password
          composer run serve &

      - name: Set up Nextcloud
        if: ${{ matrix.databases == 'pgsql'}}
        run: |
          sleep 25
          mkdir data
          ./occ maintenance:install --verbose --database=${{ matrix.databases }} --database-name=nextcloud --database-host=127.0.0.1 --database-port=$PGSQL_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass password
          composer run serve &

      - name: Enable app and app_api
        run: ./occ app:enable -vvv -f app_api

      - name: Setup python 3.10
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 #v5.5.0
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: ${{ env.APP_NAME }}/requirements.txt

      - name: Install app
        working-directory: ${{ env.APP_NAME }}
        run: |
          python3 -m pip install -r requirements.txt

      - name: Install and init backend
        working-directory: ${{ env.APP_NAME }}/ex_app/lib
        env:
          APP_VERSION: ${{ fromJson(steps.appinfo.outputs.result).version }}
          NUM_INFERENCE_STEPS: 1
        run: |
          python3 main.py > ../../backend_logs 2>&1 &

      - name: Register backend
        run: |
          ./occ app_api:daemon:register --net host manual_install "Manual Install" manual-install http localhost http://localhost:8080
          ./occ app_api:app:register text2image_stablediffusion2 manual_install --json-info "{\"appid\":\"text2image_stablediffusion2\",\"name\":\"Local image generation\",\"daemon_config_name\":\"manual_install\",\"version\":\"${{ fromJson(steps.appinfo.outputs.result).version }}\",\"secret\":\"12345\",\"port\":9080,\"scopes\":[\"AI_PROVIDERS\", \"TASK_PROCESSING\"],\"system_app\":0}" --force-scopes --wait-finish

      - name: Run task
        env:
          CREDS: "admin:password"
        run: |
          set -x
          sleep 600
          TASK=$(curl -X POST -u "$CREDS" -H "oCS-APIRequest: true" -H "Content-type: application/json" http://localhost:8080/ocs/v2.php/taskprocessing/schedule?format=json --data-raw '{"input": {"input": "An astronaut riding a horse under water", "numberOfImages": 1},"type":"core:text2image", "appId": "test", "customId": ""}')
          echo $TASK
          TASK_ID=$(echo $TASK | jq '.ocs.data.task.id')
          NEXT_WAIT_TIME=0
          TASK_STATUS='"STATUS_SCHEDULED"'
          until [ $NEXT_WAIT_TIME -eq 90 ] || [ "$TASK_STATUS" == '"STATUS_SUCCESSFUL"' ] || [ "$TASK_STATUS" == '"STATUS_FAILED"' ]; do
            TASK=$(curl -u "$CREDS" -H "oCS-APIRequest: true" http://localhost:8080/ocs/v2.php/taskprocessing/task/$TASK_ID?format=json)
            echo $TASK
            TASK_STATUS=$(echo $TASK | jq '.ocs.data.task.status')
            echo $TASK_STATUS
            sleep $(( NEXT_WAIT_TIME++ ))
          done
          curl -u "$CREDS" -H "oCS-APIRequest: true" http://localhost:8080/ocs/v2.php/taskprocessing/task/$TASK_ID?format=json
          [ "$TASK_STATUS" == '"STATUS_SUCCESSFUL"' ]

      - name: Show logs
        if: always()
        run: |
          tail data/nextcloud.log
          echo '--------------------------------------------------'
          [ -f ${{ env.APP_NAME }}/backend_logs ] && cat ${{ env.APP_NAME }}/backend_logs || echo "No backend logs"
